#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

OT_BUILDDIR="$(pwd)/build"
readonly OT_BUILDDIR

OT_OPTIONS=(
    "-DOT_COMPILE_WARNING_AS_ERROR=ON"
)
readonly OT_OPTIONS

main()
{
    export CPPFLAGS="${CPPFLAGS:-} -DNDEBUG"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52811 UART_trans "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52833 UART_trans "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52840 UART_trans "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52833 USB_trans "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52840 USB_trans "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52840 USB_trans -DOT_BOOTLOADER=USB "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52811 SPI_trans_NCP "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52833 SPI_trans_NCP "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52840 SPI_trans_NCP "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52811 RTT_trans "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52833 RTT_trans "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52840 RTT_trans "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52840 soft_crypto "${OT_OPTIONS[@]}"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build nrf52840 soft_crypto_threading "${OT_OPTIONS[@]}"
}

main "$@"
